/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiPercentageCircle {
        "pc": any;
    }
}
declare global {
    interface HTMLUiPercentageCircleElement extends Components.UiPercentageCircle, HTMLStencilElement {
    }
    var HTMLUiPercentageCircleElement: {
        prototype: HTMLUiPercentageCircleElement;
        new (): HTMLUiPercentageCircleElement;
    };
    interface HTMLElementTagNameMap {
        "ui-percentage-circle": HTMLUiPercentageCircleElement;
    }
}
declare namespace LocalJSX {
    interface UiPercentageCircle {
        "pc"?: any;
    }
    interface IntrinsicElements {
        "ui-percentage-circle": UiPercentageCircle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-percentage-circle": LocalJSX.UiPercentageCircle & JSXBase.HTMLAttributes<HTMLUiPercentageCircleElement>;
        }
    }
}
